src/experience.js
src/index.js

Here is a basic implementation of the level system based on the ExpStorage.java.
As you can see, i chose to hardcode the levels (for now, should be moved to a config file or whatever) instead of using the `generate_levels` function. I kept it in the code so that you can choose which way you want to generate/load the levels. 
Not sure if i should have used jsdoc or not, could be removed :shrug:
This is the first time i'm playing with fp so there should be many things to review.

basic level implementation

---

.prettierignore
package-lock.json
package.json
src/boss_bar.js
src/login.js
src/settings.js
src/world/codec.js

Update to minecraft 1.16.3

---

src/chunk/update.js
src/login.js
src/math.js

Remove thoses -1 everywhere
Fix free while loading chunk by fixing light inside them

Clean chunk loading code

---

src/chat.js
src/index.js

Chat show item

---

src/index.js
src/statistics.js

Little rework on statistics.js
added an CATEGORIES enum for easier work

Statistics

---

src/login.js
src/lowlife.js
src/world_border.js

Added Red_screen Control Function

World Border

---

package.json
src/index.js
src/player/inventory.js
src/player/login.js

Player Inventory

---

src/chunk/update.js
src/index.js
src/mobs.js
src/player/sync.js
src/player/tablist.js

Players can see each other

---

src/behavior.js
src/chunk/update.js
src/commands/gamemode.js
src/context.js
src/index.js
src/mobs.js
src/mobs/damage.js
src/mobs/dialog.js
src/mobs/goto.js
src/mobs/position.js
src/mobs/target.js
src/player/attributes.js
src/player/chat.js
src/player/deal_damage.js
src/player/experience.js
src/player/fall_damage.js
src/player/health.js
src/player/held_item.js
src/player/inventory.js
src/player/login.js
src/player/position.js
src/player/resource_pack.js
src/player/screen.js
src/player/statistics.js
src/player/teleportation_stones.js
src/player/traders.js
src/player/view_distance.js

To do that we dynamic import the whole state/context logic
to let the server initialize first
The server now bind to port in 500ms, the bigger slowdown
now is inside minecraft-protocol: it's the generation of
the rsa key
Fix #306

Speed up server port bind speed

---

src/mobs/movements.js

Handle movement update of more than 8 blocks

---

src/chat.js
src/commands/enjin.js
src/commands/ragequit.js
src/enjin/enjin.js

Enforce generic colors

---

src/mobs/damage.js
src/mobs/types.js

NPCs should not be able to take damage from the player

---

src/chat.js
src/commands/dislike.js
src/commands/fragile.js
src/commands/jerry.js
src/commands/like.js
src/commands/osef.js
src/commands/ragequit.js
src/commands/respect.js
src/commands/rt.js
src/commands/tg.js
src/commands/thug.js
src/player/chat.js
src/player/login.js

Show a msg when a player join for the first time

---

src/mobs/damage.js

Add invulnerability frame on entities

---

src/context.js
src/mobs.js
src/mobs/position.js
src/world.js

Fix player screen throw an error when any click is made

---

src/chat.js
src/context.js
src/player/action_bar.js
src/player_statistics.js
src/title.js

Send an action bar to the player

---

package-lock.json
package.json
script/entity_metadata.js
src/armor_stand.js
src/entity_metadata.js
src/entity_metadata.json
src/mobs/spawn.js
src/player/experience.js
src/player/item_loot.js
src/player/screen.js
src/player/teleportation_stones.js
src/player/traders.js

@DeltaEvo i just don't know how to handle bitmasks if you can commit directly on the PR to fix that 🙏 
- both the way to write them in the json (https://wiki.vg/Entity_metadata#Entity_Metadata_Format)
- and the `Bitmask()` function

Add support for entity metadata with a json file

---

data/entities.json
src/chat.js
src/context.js
src/debug.js
src/mobs.js
src/mobs/attack.js
src/mobs/behavior_tree.js
src/mobs/damage.js
src/mobs/dialog.js
src/mobs/loot.js
src/mobs/spawn.js
src/player/action_bar.js
src/player/boss_bar.js
src/player/damage.js

I isolated away the ring buffer and the lru so the code become clearer (in my pov). Commit history is cleaned

Cleaner implementation of Bossbar, damage indicator, and damage invulnerability

---

src/player/health.js

Show player health below his name

---

src/mobs/damage.js
src/mobs/spawn.js

Show mob health value in it's nametag

---

src/player/sync.js
src/player/tablist.js

fix: 🐛 State is null when 2 players join at the same time

---

src/mobs/damage.js

Avoid damaging mobs if damager's health is 0
Fix for #490

Fixed player ability to hit mobs during death timer

---

src/player/action_bar.js
src/player/chat.js
src/player/teleportation_stones.js

Added %pos% to share position in chat:
Re-implemented %item% to share item in hand:
code is probably ugly (i'm starting in nodejs) please give me advises :)

Show zone from player position & %pos%

---

src/context.js
src/player/bells.js

My first PR ever, don't really know how to structure it.
The feature is quite simple so i dont really need to explain it, i guess.

Handle right click on a bell

---

.github/workflows/fast-forward.yml
src/debug.js

https://arborist.aresrpg.world

Set arborist url to arborist.aresrpg.world

---

src/server.js
src/types.d.ts

fix: Joining with an invalid version

---

src/commands/declare_options.js
src/commands/experience.js
src/commands/health.js
src/commands/settings.js
src/commands/soul.js

Fix client crashing when using integer() command node with a min / max

---

src/player/damage.js
src/player/fall_damage.js

Support blocks that cancel fall damages

---

src/context.js
src/iterator.js
src/server.js

Prevent state errors on socket error
